ci: fix release workflow

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -6,19 +6,69 @@ name: release-please
 env:
   ACTION_NAME: vaddy-vulnerability-scan
 jobs:
+  build:
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v2
+    - name: install
+      run: npm ci
+    - name: build
+      run: npm run build
+    - name: commit
+      run: |-
+        set -e
+        # get current commit hash
+        CURRENT_HASH=$(git rev-parse HEAD)
+        # get last commit hash of last build dist
+        LAST_BUILD_HASH=$(git log --grep="^chore: build dist ${ACTION_NAME}" -1 --pretty=format:"%H")
+        DIFF=""
+        # build and commit dist if diff
+        git config --global user.name "Yuya Kusakabe"
+        git config user.email 'yuya.kusakabe@gmail.com'
+        git add dist/
+        git diff-index --quiet HEAD || git commit -m "chore: build dist ${ACTION_NAME}"
+        # if last commit hash of last build dist was found, get logs of commits in btw for PR body
+        if [ -z "$LAST_BUILD_HASH" ]
+        then
+              echo "Unable to find last commit by bot, skipping diff gen"
+        else
+              DIFF=$(git log ${LAST_BUILD_HASH}...${CURRENT_HASH} --oneline)
+              echo $DIFF
+        fi
+        # set env vars
+        echo "CURRENT_HASH=${CURRENT_HASH}" >> $GITHUB_ENV
+        echo "LAST_BUILD_HASH=${LAST_BUILD_HASH}" >> $GITHUB_ENV
+        echo 'DIFF<<EOF' >> $GITHUB_ENV
+        echo "${DIFF}" >> $GITHUB_ENV
+        echo 'EOF' >> $GITHUB_ENV
+    - name: Create PR with dist
+      uses: peter-evans/create-pull-request@v3
+      with:
+        token: ${{ secrets.ACTIONS_BOT_TOKEN }}
+        commit-message: Build dist
+        author: "higebu <yuya.kusakabe@gmail.com>"
+        title: "chore: build dist"
+        body: |
+          Build dist PR
+          ${{env.DIFF}}
+        labels: automated pr
+        branch: create-pull-request/build-dist
+        delete-branch: true
   release-please-pr:
     runs-on: ubuntu-latest
+    needs: [build]
     steps:
       - id: release-pr
         uses: GoogleCloudPlatform/release-please-action@v2
         with:
-          token: ${{ secrets.GITHUB_TOKEN }}
+          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
           release-type: node
+          fork: true
           package-name: ${{env.ACTION_NAME}}
           command: release-pr
       - id: label
         if: ${{ steps.release-pr.outputs.pr }}
-        uses: actions/github-script@v4
+        uses: actions/github-script@v3
         with:
             github-token: ${{secrets.GITHUB_TOKEN}}
             script: |
@@ -30,18 +80,19 @@ jobs:
                 labels: ['autorelease: pending']
               });
               console.log(`Tagged ${{steps.release-pr.outputs.pr}}`)
-  release-please:
+  release-please-release:
     runs-on: ubuntu-latest
+    needs: [build]
     steps:
       - uses: GoogleCloudPlatform/release-please-action@v2
         id: release
         with:
+          token: ${{ secrets.GITHUB_TOKEN }}
           release-type: node
           package-name: ${{env.ACTION_NAME}}
           command: github-release
       - uses: actions/checkout@v2
       - name: tag major and patch versions
-        if: ${{ steps.release.outputs.release_created }}
         run: |
           git config user.name github-actions[bot]
           git config user.email 41898282+github-actions[bot]@users.noreply.github.com
@@ -54,3 +105,4 @@ jobs:
           git tag -a v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} -m "Release v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}"
           git push origin v${{ steps.release.outputs.major }}
           git push origin v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}
+        if: ${{ steps.release.outputs.release_created }}
